permalink:           pretty

# Setup
title:               m4rw3r
tagline:             The blog of Martin Wernstål
url:                 http://m4rw3r.github.io/
paginate:            1
baseurl:             ""
markdown:            kramdown
gems:                ["jekyll-paginate"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Martin Wernstål
  email:             m4rw3r@gmail.com
